# docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile_3_10_alpine -t prikid/docker_python_scrapy_selenium_geckodriver:3.10-alpine --push .

FROM --platform=$BUILDPLATFORM rust:alpine AS geckodriver
RUN apk add curl build-base \
#    && GECKODRIVER_VERSION=`curl https://github.com/mozilla/geckodriver/releases/latest | grep -oE '[0-9]+.[0-9]+.[0-9]+'` \
    && GECKODRIVER_VERSION="0.33.0" \
    && wget https://github.com/mozilla/geckodriver/archive/refs/tags/v$GECKODRIVER_VERSION.tar.gz -O geckodriver.tar.gz \
    && tar -zxf geckodriver.tar.gz \
    && cd geckodriver-$GECKODRIVER_VERSION \
    && cargo build --release \
    && cp target/release/geckodriver /

FROM --platform=$BUILDPLATFORM python:3.10-alpine
ENV PYTHONUNBUFFERED=1 \
    WEBDRIVER_PATH="/usr/local/bin/geckodriver" \
    FIREFOX_BIN="/usr/bin/firefox"
COPY --from=geckodriver /geckodriver /usr/local/bin
RUN --mount=type=cache,target=/root/.cache/pip \
    apk add --update --no-cache --virtual .build-deps g++ gcc libxml2-dev libxslt libxslt-dev libffi-dev libpq-dev \
    && apk add --no-cache libxslt libpq firefox-esr \
    && pip install --no-cache-dir Scrapy=2.10.1 selenium=4.9.1 scrapy-selenium=0.0.7 itemloaders=1.1.0 itemadapter=0.8.0  \
    psycopg2==2.9.7 SQLAlchemy=1.4.49 pandas=2.1.0 rq=1.15.1 redis=5.0.0 python-dotenv=1.0.0 python-dateutil=2.8.2 \
    && apk del .build-deps