# docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile_slim_bullseye -t prikid/docker_python_scrapy_selenium_geckodriver:slim-bullseye --push .

FROM --platform=$BUILDPLATFORM rust:slim-bullseye AS geckodriver
RUN apt-get update && apt-get install -y --no-install-recommends curl wget \
    && GECKODRIVER_VERSION=`curl https://github.com/mozilla/geckodriver/releases/latest | grep -oE '[0-9]+.[0-9]+.[0-9]+'` \
    && wget https://github.com/mozilla/geckodriver/archive/refs/tags/v$GECKODRIVER_VERSION.tar.gz -O geckodriver.tar.gz \
    && tar -zxf geckodriver.tar.gz \
    && cd geckodriver-$GECKODRIVER_VERSION \
    && cargo build --release \
    && cp target/release/geckodriver / \
    && rm -rf /var/lib/apt/lists/*

FROM --platform=$BUILDPLATFORM python:3.9-slim-bullseye
ENV PYTHONUNBUFFERED=1 \
    WEBDRIVER_PATH="/usr/local/bin/geckodriver" \
    FIREFOX_BIN="/usr/bin/firefox"
COPY --from=geckodriver /geckodriver /usr/local/bin
RUN apt-get update && apt-get install -y --no-install-recommends firefox-esr \
    && pip install --no-cache-dir Scrapy selenium scrapy-selenium itemloaders itemadapter