FROM python:3.9
ARG DEBIAN_FRONTEND=noninteractive

# configuration for armv7 processors
RUN apt-get update \
    && apt-get install --no-install-recommends -y libxtst6 libasound2 libgtk-3-0 libdbus-glib-1-2 libx11-xcb-dev libpci-dev \
    gcc-arm-linux-gnueabihf libc6-armhf-cross libc6-dev-armhf-cross \
    && rm -rf /var/lib/apt/lists/* \
    && echo "===> Installing geckodriver and firefox..." \


    && GECKODRIVER_VERSION=`curl https://github.com/mozilla/geckodriver/releases/latest | grep -Po 'v[0-9]+.[0-9]+.[0-9]+'` \
    && wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz \
    && tar -zxf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C /usr/local/bin \
    && chmod +x /usr/local/bin/geckodriver \
    && rm geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz \
    \
    && FIREFOX_SETUP=firefox-setup.tar.bz2 \
    && wget -O $FIREFOX_SETUP "https://download.mozilla.org/?product=firefox-latest&os=linux64" \
    && tar xjf $FIREFOX_SETUP -C /opt/ \
    && ln -s /opt/firefox/firefox /usr/bin/firefox \
    && rm $FIREFOX_SETUP \
    \
    && echo "===> Installing python dependencies..." \
    && pip install -r Scrapy selenium scrapy-selenium itemloaders itemadapter


ENV PYTHONUNBUFFERED=1
ENV WEBDRIVER_PATH="/usr/local/bin/geckodriver"
ENV FIREFOX_BIN="/usr/bin/firefox"
